### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by brendenpalmer**

### CODE REVIEW

**Comment by scalvert** [comment]
This is great. We should setup dependabot on this repo. Also, it's probably worth running `ember init` on this repo to update to the latest blueprint. Also also, is there a reason we have both a `package-lock.json` _and_ a `yarn.lock`?

**Comment by stefanpenner** [comment]
Lgtm

**Comment by brendenpalmer** [comment]
@scalvert I've updated this PR after running `ember init` so it's on the latest blueprint. Also, there shouldn't be both a `yarn.lock` and a `package-lock.json`. Since we're using yarn on this repo I've removed `package-lock.json`.

**Comment by scalvert** [comment]
LGTM! 👍

**Pull request merged**
